insert into "Professions" ("Name", "CategoryId") values ('Moler', 1);
insert into "Professions" ("Name", "CategoryId") values ('Gipsar', 1);
insert into "Professions" ("Name", "CategoryId") values ('Fasader', 1);
insert into "Professions" ("Name", "CategoryId") values ('Zidar', 1);
insert into "Professions" ("Name", "CategoryId") values ('Parketar', 1);
insert into "Professions" ("Name", "CategoryId") values ('Keramicar', 1);
insert into "Professions" ("Name", "CategoryId") values ('Gradjevinski limar', 1);
insert into "Professions" ("Name", "CategoryId") values ('Varilac', 1);
insert into "Professions" ("Name", "CategoryId") values ('Gradjevinski stolar', 1);
insert into "Professions" ("Name", "CategoryId") values ('Izolater', 1);
insert into "Professions" ("Name", "CategoryId") values ('Tesar', 1);
insert into "Professions" ("Name", "CategoryId") values ('Izrada bazena i fontana', 1);
insert into "Professions" ("Name", "CategoryId") values ('Pomocni radnik', 1);
insert into "Professions" ("Name", "CategoryId") values ('Postavljanje podnih povrsina', 1);
insert into "Professions" ("Name", "CategoryId") values ('Secenje i busenje', 1);
insert into "Professions" ("Name", "CategoryId") values ('Armirac', 1);
insert into "Professions" ("Name", "CategoryId") values ('Bravar-monter', 1);
insert into "Professions" ("Name", "CategoryId") values ('Elektricar', 2);
insert into "Professions" ("Name", "CategoryId") values ('Vikler elektromotora', 2);
insert into "Professions" ("Name", "CategoryId") values ('Serviser liftova', 2);
insert into "Professions" ("Name", "CategoryId") values ('Monter klima uredjaja', 2);
insert into "Professions" ("Name", "CategoryId") values ('Audio-video serviser', 2);
insert into "Professions" ("Name", "CategoryId") values ('Serviser mobilnih telefona', 2);
insert into "Professions" ("Name", "CategoryId") values ('Serviser racunara', 2);
insert into "Professions" ("Name", "CategoryId") values ('Spremacica', 3);
insert into "Professions" ("Name", "CategoryId") values ('Cistac', 3);
insert into "Professions" ("Name", "CategoryId") values ('Perac podnih povrsina', 3);
insert into "Professions" ("Name", "CategoryId") values ('Odzacar', 3);
insert into "Professions" ("Name", "CategoryId") values ('Bastovan', 3);
insert into "Professions" ("Name", "CategoryId") values ('Drvoseca', 3);
insert into "Professions" ("Name", "CategoryId") values ('Visinski radnik', 3);
insert into "Professions" ("Name", "CategoryId") values ('Perac fasada', 3);
insert into "Professions" ("Name", "CategoryId") values ('Haus majstor/Domar', 3);
insert into "Professions" ("Name", "CategoryId") values ('Vodoinstalater', 4);
insert into "Professions" ("Name", "CategoryId") values ('Monter grejnih instalacija', 4);
insert into "Professions" ("Name", "CategoryId") values ('Ventilacioni sistemi', 4);
insert into "Professions" ("Name", "CategoryId") values ('Kljucar', 5);
insert into "Professions" ("Name", "CategoryId") values ('Tapetar', 5);
insert into "Professions" ("Name", "CategoryId") values ('Metalostrugar', 5);
insert into "Professions" ("Name", "CategoryId") values ('Stolar', 5);
insert into "Professions" ("Name", "CategoryId") values ('Staklorezac', 5);
insert into "Professions" ("Name", "CategoryId") values ('Grncar', 5);
insert into "Professions" ("Name", "CategoryId") values ('Kamenorezac', 5);
insert into "Professions" ("Name", "CategoryId") values ('Masin-bravar', 5);
insert into "Professions" ("Name", "CategoryId") values ('Kovac', 5);
insert into "Professions" ("Name", "CategoryId") values ('Povrsinska obrada', 5);
insert into "Professions" ("Name", "CategoryId") values ('Livac', 5);
insert into "Professions" ("Name", "CategoryId") values ('Uramljivac', 5);
insert into "Professions" ("Name", "CategoryId") values ('Metaloglodac', 5);
insert into "Professions" ("Name", "CategoryId") values ('Metaloostrac', 5);
insert into "Professions" ("Name", "CategoryId") values ('Pecatorezac', 5);
insert into "Professions" ("Name", "CategoryId") values ('Krojac', 6);
insert into "Professions" ("Name", "CategoryId") values ('Obucar', 6);
insert into "Professions" ("Name", "CategoryId") values ('Tasner', 6);
insert into "Professions" ("Name", "CategoryId") values ('Sajdzija-Casovnicar', 6);
insert into "Professions" ("Name", "CategoryId") values ('Juvelir-Zlatar', 6);
insert into "Professions" ("Name", "CategoryId") values ('Masinski vez', 6);
insert into "Professions" ("Name", "CategoryId") values ('Rucni vez', 6);
insert into "Professions" ("Name", "CategoryId") values ('Krznar', 6);
insert into "Professions" ("Name", "CategoryId") values ('Sesirdzija', 6);
insert into "Professions" ("Name", "CategoryId") values ('Serviser sivacih masina', 6);
insert into "Professions" ("Name", "CategoryId") values ('Auto elektricar', 7);
insert into "Professions" ("Name", "CategoryId") values ('Auto limar', 7);
insert into "Professions" ("Name", "CategoryId") values ('Auto bravar', 7);
insert into "Professions" ("Name", "CategoryId") values ('Auto mehanicar', 7);
insert into "Professions" ("Name", "CategoryId") values ('Serviser autogas sistema', 7);
insert into "Professions" ("Name", "CategoryId") values ('Auto graficar', 7);
insert into "Professions" ("Name", "CategoryId") values ('Auto tapetar', 7);
insert into "Professions" ("Name", "CategoryId") values ('Auto perac', 7);
insert into "Professions" ("Name", "CategoryId") values ('Vulkanizer', 7);
insert into "Professions" ("Name", "CategoryId") values ('Slep sluzba', 7);
insert into "Professions" ("Name", "CategoryId") values ('Serviser trapa', 7);
insert into "Professions" ("Name", "CategoryId") values ('Auto stakla', 7);
insert into "Professions" ("Name", "CategoryId") values ('Auto plasticar', 7);
insert into "Professions" ("Name", "CategoryId") values ('Serviser auspuha', 7);
insert into "Professions" ("Name", "CategoryId") values ('Serviser motocikala', 7);
insert into "Professions" ("Name", "CategoryId") values ('Vozac', 8);
insert into "Professions" ("Name", "CategoryId") values ('Transport selidbi', 8);
insert into "Professions" ("Name", "CategoryId") values ('Fizicki radnik', 8);
insert into "Professions" ("Name", "CategoryId") values ('Graficar', 8);
insert into "Professions" ("Name", "CategoryId") values ('Firmopisac', 8);
insert into "Professions" ("Name", "CategoryId") values ('Ikonopisac', 8);
insert into "Professions" ("Name", "CategoryId") values ('Serviser za bicikle', 8);
insert into "Professions" ("Name", "CategoryId") values ('Ski serviser', 8);
insert into "Professions" ("Name", "CategoryId") values ('Serviser medicinske opreme', 8);
insert into "Professions" ("Name", "CategoryId") values ('Roletne i venecijaneri', 8);
