insert into "Trades" ("Name", "ProfessionId") values ('Krecenje', 1);
insert into "Trades" ("Name", "ProfessionId") values ('Gletovanje', 1);
insert into "Trades" ("Name", "ProfessionId") values ('Farbanje stolarije', 1);
insert into "Trades" ("Name", "ProfessionId") values ('Farbanje radijatora i cevi', 1);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje zidnih lajsni', 1);
insert into "Trades" ("Name", "ProfessionId") values ('Spatulat', 1);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje gipsanih ploca', 2);
insert into "Trades" ("Name", "ProfessionId") values ('Pregradjivanje prostorija', 2);
insert into "Trades" ("Name", "ProfessionId") values ('Spustanje plafona', 2);
insert into "Trades" ("Name", "ProfessionId") values ('Pravljenje dekorativnih lukova', 2);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada sankova', 2);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje fasade', 3);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje izolacije', 3);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje mermernih fasada', 3);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje kamenih fasada', 3);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje fasadne cigle', 3);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje dekorativnog kamena', 3);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje fasadne mrezice', 3);
insert into "Trades" ("Name", "ProfessionId") values ('Zidanje u niskogradnji', 4);
insert into "Trades" ("Name", "ProfessionId") values ('Zidanje u visokogradnji', 4);
insert into "Trades" ("Name", "ProfessionId") values ('Malterisanje', 4);
insert into "Trades" ("Name", "ProfessionId") values ('Zidanje kamina i pecenjara', 4);
insert into "Trades" ("Name", "ProfessionId") values ('Zidanje i ciscenje kaljevih peci', 4);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje parketa', 5);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje laminata', 5);
insert into "Trades" ("Name", "ProfessionId") values ('Hoblovanje parketa', 5);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje lajsni', 5);
insert into "Trades" ("Name", "ProfessionId") values ('Lakiranje parketa', 5);
insert into "Trades" ("Name", "ProfessionId") values ('Brodski pod', 5);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje plocica', 6);
insert into "Trades" ("Name", "ProfessionId") values ('Skidanje plocica', 6);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada oluka i okapnica', 7); 
insert into "Trades" ("Name", "ProfessionId") values ('Izrada snegobrana', 7); 
insert into "Trades" ("Name", "ProfessionId") values ('Izrada krovova', 7); 
insert into "Trades" ("Name", "ProfessionId") values ('Izrada vetrobrana', 7); 
insert into "Trades" ("Name", "ProfessionId") values ('Izrada odusaka', 7); 
insert into "Trades" ("Name", "ProfessionId") values ('Letovanje', 7); 
insert into "Trades" ("Name", "ProfessionId") values ('Izrada vetar lajsni', 7); 
insert into "Trades" ("Name", "ProfessionId") values ('Izrada iksni i oksni', 7);
insert into "Trades" ("Name", "ProfessionId") values ('Elektrolucno varenje', 8);
insert into "Trades" ("Name", "ProfessionId") values ('Argonsko i CO2 varenje', 8);
insert into "Trades" ("Name", "ProfessionId") values ('Autogeno varenje', 8);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i ugradnja PVC stolarije', 9);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i ugradnja ALU stolarije', 9);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i ugradnja drvene stolarije', 9);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i ugradnja komarnika', 9);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i ugradnja roletni', 9);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i ugradnja zaluzina', 9);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i ugradnja venecijanera', 9);
insert into "Trades" ("Name", "ProfessionId") values ('Popravke na stolariji', 9);
insert into "Trades" ("Name", "ProfessionId") values ('Hidroizolacija', 10);
insert into "Trades" ("Name", "ProfessionId") values ('Termoizolacija', 10);
insert into "Trades" ("Name", "ProfessionId") values ('Drenaza', 10);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada rogova', 11);
insert into "Trades" ("Name", "ProfessionId") values ('Salovanje temelja i stubova', 11);
insert into "Trades" ("Name", "ProfessionId") values ('Opsivanje krovova', 11);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje crepa', 11);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i primena oplate', 11);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada skela', 11);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada krovnih konstrukcija od drveta', 11);
insert into "Trades" ("Name", "ProfessionId") values ('Priprema i obrada drvne gradje', 11);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada potpornih konstrukcija', 11);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada bazena', 12);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada fontana', 12);
insert into "Trades" ("Name", "ProfessionId") values ('Ispomoc na gradilistu', 13);
insert into "Trades" ("Name", "ProfessionId") values ('Ravnajuci sloj/kosuljica', 14);
insert into "Trades" ("Name", "ProfessionId") values ('Industrijski pod', 14);
insert into "Trades" ("Name", "ProfessionId") values ('Sportske podloge', 14);
insert into "Trades" ("Name", "ProfessionId") values ('Vestacka trava', 14);
insert into "Trades" ("Name", "ProfessionId") values ('Behaton beton', 14);
insert into "Trades" ("Name", "ProfessionId") values ('Stampani podovi', 14);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada trotoara', 14);
insert into "Trades" ("Name", "ProfessionId") values ('Dijamantsko busenje rupa', 15);
insert into "Trades" ("Name", "ProfessionId") values ('Secenje armature', 15);
insert into "Trades" ("Name", "ProfessionId") values ('Busenje greda', 15);
insert into "Trades" ("Name", "ProfessionId") values ('Busenje betona', 15);
insert into "Trades" ("Name", "ProfessionId") values ('Probijanje zidova', 15);
insert into "Trades" ("Name", "ProfessionId") values ('Secenje asfalta', 15);
insert into "Trades" ("Name", "ProfessionId") values ('Pneumatsko busenje', 15);
insert into "Trades" ("Name", "ProfessionId") values ('Rusenje', 15);
insert into "Trades" ("Name", "ProfessionId") values ('Busenje bunara', 15);
insert into "Trades" ("Name", "ProfessionId") values ('Prokopavanje zemlje(krtica)', 15);
insert into "Trades" ("Name", "ProfessionId") values ('Spajanje armature', 16);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada armature', 16);
insert into "Trades" ("Name", "ProfessionId") values ('Izlivanje betona', 16);
insert into "Trades" ("Name", "ProfessionId") values ('Armiranje betona', 16);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada okova', 17);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada gelendera', 17);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada ograda', 17);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada nosaca', 17);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada nadstresnica', 17);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada kapija', 17);
insert into "Trades" ("Name", "ProfessionId") values ('Montaza panela', 17);
insert into "Trades" ("Name", "ProfessionId") values ('Montaza krovnih pokrivaca', 17);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje elektricnih instalacija', 18);
insert into "Trades" ("Name", "ProfessionId") values ('Detektovanje kvara na elektricnoj mrezi', 18);
insert into "Trades" ("Name", "ProfessionId") values ('Servis malih kucnih aparata', 18);
insert into "Trades" ("Name", "ProfessionId") values ('Servis bele tehnike', 18);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje rasvete', 18);
insert into "Trades" ("Name", "ProfessionId") values ('Servis ves masina', 18);
insert into "Trades" ("Name", "ProfessionId") values ('Servis bojlera', 18);
insert into "Trades" ("Name", "ProfessionId") values ('Servis TA peci', 18);
insert into "Trades" ("Name", "ProfessionId") values ('Servis vodenih pumpi', 18);
insert into "Trades" ("Name", "ProfessionId") values ('Viklovanje elektromotora', 19);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja liftova', 20);
insert into "Trades" ("Name", "ProfessionId") values ('Odrzavanje liftova', 20);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja pokretnih stepenica', 20);
insert into "Trades" ("Name", "ProfessionId") values ('Odrzavanje pokretnih stepenica', 20);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje klima uredjaja', 21);
insert into "Trades" ("Name", "ProfessionId") values ('Servis klima uredjaja', 21);
insert into "Trades" ("Name", "ProfessionId") values ('Popravljanje televizora', 22);
insert into "Trades" ("Name", "ProfessionId") values ('Popravljanje video i DVD uredjaja', 22);
insert into "Trades" ("Name", "ProfessionId") values ('Popravljanje audio uredjaja', 22);
insert into "Trades" ("Name", "ProfessionId") values ('Popravljanje projektora', 22);
insert into "Trades" ("Name", "ProfessionId") values ('Uvodjenje i servis interfona i video nadzora', 22);
insert into "Trades" ("Name", "ProfessionId") values ('Servis foto-aparata i kamkodera', 22);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja i popravka satelitskih antena', 22);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja i popravka protivprovalne zastite', 22);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja i popravka alarmnih sistema', 22);
insert into "Trades" ("Name", "ProfessionId") values ('Popravljanje fiskalnih kasa', 22);
insert into "Trades" ("Name", "ProfessionId") values ('Popravljanje mobilnih telefona', 23);
insert into "Trades" ("Name", "ProfessionId") values ('Dekodiranje mobilnih telefona', 23);
insert into "Trades" ("Name", "ProfessionId") values ('Popravljanje navigacionih uredjaja', 23);
insert into "Trades" ("Name", "ProfessionId") values ('Servis desktop racunara', 24);
insert into "Trades" ("Name", "ProfessionId") values ('Servis laptop racunara', 24);
insert into "Trades" ("Name", "ProfessionId") values ('Instaliranje programa', 24);
insert into "Trades" ("Name", "ProfessionId") values ('Umrezavanje racunara', 24);
insert into "Trades" ("Name", "ProfessionId") values ('Instaliranje i reinstaliranje sistema', 24);
insert into "Trades" ("Name", "ProfessionId") values ('Kucna pomocnica', 25);
insert into "Trades" ("Name", "ProfessionId") values ('Ciscenje kuca i stanova', 25);
insert into "Trades" ("Name", "ProfessionId") values ('Ciscenje poslovnih prostora', 25);
insert into "Trades" ("Name", "ProfessionId") values ('Ciscenje podruma i tavana', 26);
insert into "Trades" ("Name", "ProfessionId") values ('Odnosenje suta', 26);
insert into "Trades" ("Name", "ProfessionId") values ('Ciscenje snega i leda', 26);
insert into "Trades" ("Name", "ProfessionId") values ('Pranje tepiha', 27);
insert into "Trades" ("Name", "ProfessionId") values ('Pranje podova', 27);
insert into "Trades" ("Name", "ProfessionId") values ('Poliranje podova', 27);
insert into "Trades" ("Name", "ProfessionId") values ('Ciscenje i odrzavanje odzaka', 28);
insert into "Trades" ("Name", "ProfessionId") values ('Ciscenje ventilacionih sistema', 28);
insert into "Trades" ("Name", "ProfessionId") values ('Ciscenje kotlovskih postrojenja', 28);
insert into "Trades" ("Name", "ProfessionId") values ('Odrzavanje cvetnih vrtova', 29);
insert into "Trades" ("Name", "ProfessionId") values ('Kosenje trave', 29);
insert into "Trades" ("Name", "ProfessionId") values ('Sejanje i presadjivanje trave', 29);
insert into "Trades" ("Name", "ProfessionId") values ('Orezivanje zive ograde', 29);
insert into "Trades" ("Name", "ProfessionId") values ('Orezivanje i kalemljenje vocki', 29);
insert into "Trades" ("Name", "ProfessionId") values ('Cepanje drva', 30);
insert into "Trades" ("Name", "ProfessionId") values ('Krcenje sume', 30);
insert into "Trades" ("Name", "ProfessionId") values ('Krcenje siprazja', 30);
insert into "Trades" ("Name", "ProfessionId") values ('Pranje prozora', 31);
insert into "Trades" ("Name", "ProfessionId") values ('Pranje fasada', 31);
insert into "Trades" ("Name", "ProfessionId") values ('Popravke na fasadi', 31);
insert into "Trades" ("Name", "ProfessionId") values ('Ciscenje oluka', 31);
insert into "Trades" ("Name", "ProfessionId") values ('Visinski radovi', 31);
insert into "Trades" ("Name", "ProfessionId") values ('Pranje fasada pod pritiskom', 32);
insert into "Trades" ("Name", "ProfessionId") values ('Skidanje grafita', 32);
insert into "Trades" ("Name", "ProfessionId") values ('Peskiranje fasada', 32);
insert into "Trades" ("Name", "ProfessionId") values ('Sitne popravke po kucnim aparatima', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena prekidaca, uticnica i utikaca', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena osiguraca', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena sijalicnih grla i lustera', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena grejaca u bojleru', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Popravka vodokotlica', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena slavina, tuseva, sifona i ventila', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Stelovanje sarki na vratima i prozorima', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Popravka roletni i zaluzina', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena brava', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Kacenje polica, slika, nosaca za tv', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Punjenje i praznjenje sistema za grejanje', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Sastavljanje i rastavljanje namestaja', 33);
insert into "Trades" ("Name", "ProfessionId") values ('Postavljanje vodovodne instalacije', 34);
insert into "Trades" ("Name", "ProfessionId") values ('Servis vodovodnih instalacija', 34);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena slavina, baterija i tuseva', 34);
insert into "Trades" ("Name", "ProfessionId") values ('Odgusenje odvoda', 34);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena bojlera', 34);
insert into "Trades" ("Name", "ProfessionId") values ('Detekcija curenja', 34);
insert into "Trades" ("Name", "ProfessionId") values ('Montiranje grejnih instalacija', 35);
insert into "Trades" ("Name", "ProfessionId") values ('Montiranje grejnih tela', 35);
insert into "Trades" ("Name", "ProfessionId") values ('Servis grejnih instalacija', 35);
insert into "Trades" ("Name", "ProfessionId") values ('Projektovanje ventilacionih sistema', 36);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i ugradnja ventilacionih sistema', 36);
insert into "Trades" ("Name", "ProfessionId") values ('Servisiranje ventilacionih sistema', 36);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada kljuceva', 37);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja brava', 37);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja sigurnosnih brava', 37);
insert into "Trades" ("Name", "ProfessionId") values ('Obijanje brava bez ostecenja', 37);
insert into "Trades" ("Name", "ProfessionId") values ('Tapaciranje svih vrsta namestaja', 38);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i popravka cerada', 38);
insert into "Trades" ("Name", "ProfessionId") values ('Masinska obrada metala', 39);
insert into "Trades" ("Name", "ProfessionId") values ('Obrada osovina', 39);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada namestaja po meri', 40);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada kuhinja po meri', 40);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada stilskog namestaja', 40);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada kreveta po meri', 40);
insert into "Trades" ("Name", "ProfessionId") values ('Rezbarenje i duborez', 40);
insert into "Trades" ("Name", "ProfessionId") values ('Lakiranje namestaja', 40);
insert into "Trades" ("Name", "ProfessionId") values ('Restauracija namestaja', 40);
insert into "Trades" ("Name", "ProfessionId") values ('Trakslerske usluge', 40);
insert into "Trades" ("Name", "ProfessionId") values ('Secenje stakla po meri', 41);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada ogledala po meri', 41);
insert into "Trades" ("Name", "ProfessionId") values ('Peskiranje stakla', 41);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada posuda od gline', 42);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada upotrebne keramike', 42);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada ukrasne keramike', 42);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada spomenika', 43);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada nadgrobnih ploca', 43);
insert into "Trades" ("Name", "ProfessionId") values ('Obrada kamena', 43);
insert into "Trades" ("Name", "ProfessionId") values ('Odrzavanje masina i sklopova', 44);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja masina i sklopova', 44);
insert into "Trades" ("Name", "ProfessionId") values ('Kovanje', 45);
insert into "Trades" ("Name", "ProfessionId") values ('Potkivanje', 45);
insert into "Trades" ("Name", "ProfessionId") values ('Peskiranje', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Smirglanje', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Niklovanje', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Hromiranje', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Plastificiranje', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Matiranje', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Bruniranje', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Cinkovanje', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Bakarisanje', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Srebrenje', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Pozlata', 46);
insert into "Trades" ("Name", "ProfessionId") values ('Livenje', 47);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada kalupa za livenje', 47);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada ramova za slike', 48);
insert into "Trades" ("Name", "ProfessionId") values ('Uramljivanje slika', 48);
insert into "Trades" ("Name", "ProfessionId") values ('Uramljivanje ogledala', 48);
insert into "Trades" ("Name", "ProfessionId") values ('Obrada zupcanika', 49);
insert into "Trades" ("Name", "ProfessionId") values ('Obrada zlebova', 49);
insert into "Trades" ("Name", "ProfessionId") values ('Ostrenje nozeva', 50);
insert into "Trades" ("Name", "ProfessionId") values ('Ostrenje alata', 50);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada aluminijumskih natpisa', 51);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada mesinganih natpisa', 51);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada plasticnih natpisa', 51);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada privezaka', 51);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada pecata', 51);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada plaketa', 51);
insert into "Trades" ("Name", "ProfessionId") values ('Sivenje po meri', 52);
insert into "Trades" ("Name", "ProfessionId") values ('Sve vrste prepravki na tekstilu', 52);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada obuce po meri', 53);
insert into "Trades" ("Name", "ProfessionId") values ('Sve vrste prepravki na obuci', 53);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada anatomskih ulozaka', 53);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada tasni i torbi', 54);
insert into "Trades" ("Name", "ProfessionId") values ('Prepravke na tasnama i torbama', 54);
insert into "Trades" ("Name", "ProfessionId") values ('Servis rucnih satova', 55);
insert into "Trades" ("Name", "ProfessionId") values ('Servis zidnih satova', 55);
insert into "Trades" ("Name", "ProfessionId") values ('Stelovanje narukvica', 55);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada nakita po porudzbini', 56);
insert into "Trades" ("Name", "ProfessionId") values ('Sve vrste prepravki na nakitu', 56);
insert into "Trades" ("Name", "ProfessionId") values ('Graviranje', 56);
insert into "Trades" ("Name", "ProfessionId") values ('Vez na tekstilu', 57);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada aplikacija, grbova i amblema', 57);
insert into "Trades" ("Name", "ProfessionId") values ('Heklanje', 58);
insert into "Trades" ("Name", "ProfessionId") values ('Tkanje', 58);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada goblena', 58);
insert into "Trades" ("Name", "ProfessionId") values ('Pletenje', 58);
insert into "Trades" ("Name", "ProfessionId") values ('Vezenje', 58);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada garderobe od krzna', 59);
insert into "Trades" ("Name", "ProfessionId") values ('Popravke krzna', 59);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada sesira', 60);
insert into "Trades" ("Name", "ProfessionId") values ('Reparacija sesira', 60);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada kacketa', 60);
insert into "Trades" ("Name", "ProfessionId") values ('Reparacija kacketa', 60);
insert into "Trades" ("Name", "ProfessionId") values ('Popravka sivacih masina', 61);
insert into "Trades" ("Name", "ProfessionId") values ('Auto dijagnostika', 62);
insert into "Trades" ("Name", "ProfessionId") values ('Servis elektro instalacije', 62);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja alarma i centralne brave', 62);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja audio i video sistema', 62);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja parking senzora', 62);
insert into "Trades" ("Name", "ProfessionId") values ('Auto elektronika', 62);
insert into "Trades" ("Name", "ProfessionId") values ('Ispravljanje limarije', 63);
insert into "Trades" ("Name", "ProfessionId") values ('Farbanje limarije', 63);
insert into "Trades" ("Name", "ProfessionId") values ('Prepravke na limariji', 63);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja sibera', 63);
insert into "Trades" ("Name", "ProfessionId") values ('Poliranje limarije', 63);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena auto brava', 64);
insert into "Trades" ("Name", "ProfessionId") values ('Narezivanje kljuceva', 64);
insert into "Trades" ("Name", "ProfessionId") values ('Kodiranje kljuceva', 64);
insert into "Trades" ("Name", "ProfessionId") values ('Otkljucavanje kola bez kljuca', 64);
insert into "Trades" ("Name", "ProfessionId") values ('Mehanicki radovi', 65);
insert into "Trades" ("Name", "ProfessionId") values ('Mali servis', 65);
insert into "Trades" ("Name", "ProfessionId") values ('Veliki servis', 65);
insert into "Trades" ("Name", "ProfessionId") values ('Masinska obrada motora', 65);
insert into "Trades" ("Name", "ProfessionId") values ('Masinska obrada kocionog sistema', 65);
insert into "Trades" ("Name", "ProfessionId") values ('Servis auto klime', 65);
insert into "Trades" ("Name", "ProfessionId") values ('Ciscenje dizni', 65);
insert into "Trades" ("Name", "ProfessionId") values ('Servis kamiona', 65);
insert into "Trades" ("Name", "ProfessionId") values ('Servis autobusa', 65);
insert into "Trades" ("Name", "ProfessionId") values ('Serviser poljoprivrednih masina', 65);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja plinskih uredjaja', 66);
insert into "Trades" ("Name", "ProfessionId") values ('Servis plinskih uredjaja', 66);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada i montaza auto folija', 67);
insert into "Trades" ("Name", "ProfessionId") values ('Zatamnjivanje stakala folijom', 67);
insert into "Trades" ("Name", "ProfessionId") values ('Brendiranje vozila', 67);
insert into "Trades" ("Name", "ProfessionId") values ('Stampa auto folija', 67);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada presvlaka za sve tipove vozila', 68);
insert into "Trades" ("Name", "ProfessionId") values ('Tapaciranje sedista', 68);
insert into "Trades" ("Name", "ProfessionId") values ('Tapaciranje panela na vratima', 68);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena neba u kabini', 68);
insert into "Trades" ("Name", "ProfessionId") values ('Restauracija koze', 68);
insert into "Trades" ("Name", "ProfessionId") values ('Presvlacenje volana', 68);
insert into "Trades" ("Name", "ProfessionId") values ('Presvlacenje rucice menjaca', 68);
insert into "Trades" ("Name", "ProfessionId") values ('Pranje putnickih automobila', 69);
insert into "Trades" ("Name", "ProfessionId") values ('Pranje autobusa i kamiona', 69);
insert into "Trades" ("Name", "ProfessionId") values ('Poliranje vozila', 69);
insert into "Trades" ("Name", "ProfessionId") values ('Dubinsko pranje unutrasnjosti', 69);
insert into "Trades" ("Name", "ProfessionId") values ('Servis svih vrsta pneumatika', 70);
insert into "Trades" ("Name", "ProfessionId") values ('Balansiranje guma', 70);
insert into "Trades" ("Name", "ProfessionId") values ('Ispravljanje felni', 70);
insert into "Trades" ("Name", "ProfessionId") values ('Prevoz putnickih vozila', 71);
insert into "Trades" ("Name", "ProfessionId") values ('Prevoz 2 i vise vozila', 71);
insert into "Trades" ("Name", "ProfessionId") values ('Prevoz kombi vozila', 71);
insert into "Trades" ("Name", "ProfessionId") values ('Slepovanje teretnih vozila i autobusa', 71);
insert into "Trades" ("Name", "ProfessionId") values ('Centriranje trapa', 72);
insert into "Trades" ("Name", "ProfessionId") values ('Reparacija auto stakala', 73);
insert into "Trades" ("Name", "ProfessionId") values ('Zamena auto stakala', 73);
insert into "Trades" ("Name", "ProfessionId") values ('Zatamnjivanje auto stakala', 73);
insert into "Trades" ("Name", "ProfessionId") values ('Varenje branika i spojlera', 74);
insert into "Trades" ("Name", "ProfessionId") values ('Krpljenje auspuha', 75);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada auspuha', 75);
insert into "Trades" ("Name", "ProfessionId") values ('Servis motocikala', 76);
insert into "Trades" ("Name", "ProfessionId") values ('B kategorija', 77);
insert into "Trades" ("Name", "ProfessionId") values ('C kategorija', 77);
insert into "Trades" ("Name", "ProfessionId") values ('D kategorija', 77);
insert into "Trades" ("Name", "ProfessionId") values ('E kategorija', 77);
insert into "Trades" ("Name", "ProfessionId") values ('Sopstveno vozilo', 77);
insert into "Trades" ("Name", "ProfessionId") values ('Prevoz putnika', 77);
insert into "Trades" ("Name", "ProfessionId") values ('Prevoz robe', 77);
insert into "Trades" ("Name", "ProfessionId") values ('Inostrane ture', 77);
insert into "Trades" ("Name", "ProfessionId") values ('Kurirske usluge', 77);
insert into "Trades" ("Name", "ProfessionId") values ('Transport selidbi sopstvenim vozilom', 78);
insert into "Trades" ("Name", "ProfessionId") values ('Utovar i istovar robe', 78);
insert into "Trades" ("Name", "ProfessionId") values ('Pomoc na gradjevini', 79);
insert into "Trades" ("Name", "ProfessionId") values ('Nosenje klavira', 79);
insert into "Trades" ("Name", "ProfessionId") values ('Pomoc pri selidbi', 79);
insert into "Trades" ("Name", "ProfessionId") values ('Sito stampa', 80);
insert into "Trades" ("Name", "ProfessionId") values ('Dorada stampe', 80);
insert into "Trades" ("Name", "ProfessionId") values ('Ofset stampa', 80);
insert into "Trades" ("Name", "ProfessionId") values ('Digitalna stampa', 80);
insert into "Trades" ("Name", "ProfessionId") values ('Stampa velikih formata', 80);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada svetlecih reklama', 81);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada reklamnih tabli', 81);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada reklama na ceradama', 81);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada reklamnih izloga', 81);
insert into "Trades" ("Name", "ProfessionId") values ('Kaligrafija', 81);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada ikona po zelji', 82);
insert into "Trades" ("Name", "ProfessionId") values ('Restauracija ikona', 82);
insert into "Trades" ("Name", "ProfessionId") values ('Servisiranje bicikla', 83);
insert into "Trades" ("Name", "ProfessionId") values ('Servisiranje rolera', 83);
insert into "Trades" ("Name", "ProfessionId") values ('Servisiranje skija', 84);
insert into "Trades" ("Name", "ProfessionId") values ('Servisiranje bordova', 84);
insert into "Trades" ("Name", "ProfessionId") values ('Servisiranje pancerica', 84);
insert into "Trades" ("Name", "ProfessionId") values ('Servis medicinskih aparata', 85);
insert into "Trades" ("Name", "ProfessionId") values ('Servis stomatoloske opreme', 85);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada roletni', 86);
insert into "Trades" ("Name", "ProfessionId") values ('Izrada venecijanera', 86);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja roletni', 86);
insert into "Trades" ("Name", "ProfessionId") values ('Ugradnja venecijanera', 86);
insert into "Trades" ("Name", "ProfessionId") values ('Popravka roletni', 86);
insert into "Trades" ("Name", "ProfessionId") values ('Popravka venecijanera', 86);
